package fileOperation

func ErrorExercise() {
	//error := errors.New("你遇到了一个错误")
	//fmt.Println(error.Error())
	//
	//error1 := fmt.Errorf("fmt提供的错误")
	//fmt.Println(error1.Error())
	//
	//defer func() {
	//	fmt.Println(recover())
	//}()
	//
	//var p *int
	//fmt.Println(*p)

}
